# Generated by Django 4.2.8 on 2024-01-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
