# Generated by Django 4.2.8 on 2024-01-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_laptop_name_laptop_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
