# Generated by Django 4.2.8 on 2024-02-02 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_addtocart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='mobile',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{0,9}$')]),
        ),
    ]
