# Generated by Django 4.2.8 on 2024-03-01 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_alter_userdetails_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='pin',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$')]),
        ),
    ]
